### ISSUE TITLE
Mismatch the shape on axis 2

### ISSUE THREAD

**Issue by paolopiano1997** [chriskavanagh97/FinalYearapp#1]
Hey, I saw a your comment in a post about the title error. How did you fix the issue? What is this project about? Thank you

**Comment by chriskavanagh97** [comment]
Hi, 

I couldn't figure it out, I ended up l using a different tensorflow example but now that I have more experience I think i was calling the model.tflite file and labeks.txt file wrong.

You have to ensure anywhere these are called correctly and ensure the machine learning mode you are using is compatible with your code in android.

It is an environmental educational android app

**Comment by paolopiano1997** [comment]
Another question is: how can I create a right labels.txt? I have to create a Handwritten Text Recognition and I have a shape 1024,128,4... How can I use labels.txt? For me it's not necessary but I don't know...sorry and thank you very much

**Comment by chriskavanagh97** [comment]
I'm not familiar with how the handwritten text recognition works, you should try find the documentation on tensorflow and it will probably point out the error to you
